package enums;

public enum MenuState {
    LOGIN_REGISTER, MAIN_MENU, PLAY_MENU, SHOP, GREENHOUSE, IN_GAME,
    PROFILE, COLLECTION, NEWS, LEADERBOARD, SETTINGS, TRAVEL_LOG,
    PLANT_SELECTION, MINIGAME
}
