package model.entity.zombie;

public enum ZombieType {
    // basic
    BASIC, CONEHEAD, BUCKETHEAD, BRICKHEAD, GARGANTUAR, IMP, FLAG,

    // ancient egypt
    MUMMY, MUMMY_CONE, MUMMY_BUCKET, MUMMY_BRICK,
    RA_ZOMBIE, EXPLORER, TOMB_RAISER, EGYPT_GARGANTUAR, EGYPT_IMP,

    // frostbite caves
    ICEAGE, ICEAGE_CONE, ICEAGE_BUCKET, ICEAGE_ARMOR3,
    HUNTER, TROGLOBITE, DODO_RIDER,
    ICEAGE_GARGANTUAR, ICEAGE_IMP,

    // big wave beach
    BEACH, BEACH_CONE, BEACH_BUCKET,
    SNORKEL, FISHERMAN, OCTOPUS,
    BEACH_GARGANTUAR, BEACH_IMP,

    // Dark Ages
    DARK, DARK_CONE, DARK_BUCKET, KNIGHT, DARK_BRICK,
    WIZARD, JUGGLER, KING, DARK_GARGANTUAR, DARK_IMP, DRAGON_IMP,

    // special zombies
    ALL_STAR, ARCADE, NEWSPAPER, PROSPECTOR, PIANIST,

    // zombosses
    ZOMBOSS_EGYPT, ZOMBOSS_PIRATE, ZOMBOSS_COWBOY, ZOMBOSS_DARK
}